name = "story_bakery/replicated_instance_id"
version = "0.1.0"
license = "MIT"
includes = ["pesde.toml", "LICENSE", "README.md", ".pesde/scripts/roblox_sync_config_generator.luau", ".pesde/scripts/sourcemap_generator.luau", "src/**/*.luau", "src/**/*.json", "tests/**/*.luau"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = [
    "src",
]

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
Promise = { wally = "evaera/promise", version = "^4.0.0" }
base91 = { wally = "dekkonot/base91", version = "^1.1.0" }

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"
